#!/bin/bash
#Use this file to run commands after the build.

#Let's say I want to clone a repository of my work so I can edit my files and push my changes back to GitHub.
git clone https://github.com/wp-cdas/ExampleRepo.git
